// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApWfKAZBKGpVZA0eMhResYfzjJExmY0m0',
    appId: '1:316215460819:web:219115f95221fc90096526',
    messagingSenderId: '316215460819',
    projectId: 'cropvisionsystem',
    authDomain: 'cropvisionsystem.firebaseapp.com',
    storageBucket: 'cropvisionsystem.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlhtOlAPiAXWS7l1tQm4qJM67CtpuhtbU',
    appId: '1:316215460819:android:3291bc22e30a47aa096526',
    messagingSenderId: '316215460819',
    projectId: 'cropvisionsystem',
    storageBucket: 'cropvisionsystem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBru1gOmshR5sQ_dWCPWdvtY78D_Ya1L6s',
    appId: '1:316215460819:ios:d7a4d0c10b3cdc5c096526',
    messagingSenderId: '316215460819',
    projectId: 'cropvisionsystem',
    storageBucket: 'cropvisionsystem.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBru1gOmshR5sQ_dWCPWdvtY78D_Ya1L6s',
    appId: '1:316215460819:ios:d7a4d0c10b3cdc5c096526',
    messagingSenderId: '316215460819',
    projectId: 'cropvisionsystem',
    storageBucket: 'cropvisionsystem.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApWfKAZBKGpVZA0eMhResYfzjJExmY0m0',
    appId: '1:316215460819:web:219115f95221fc90096526',
    messagingSenderId: '316215460819',
    projectId: 'cropvisionsystem',
    authDomain: 'cropvisionsystem.firebaseapp.com',
    storageBucket: 'cropvisionsystem.firebasestorage.app',
  );
}
